name: aimtech
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.4
  http: ^1.3.0
  provider: ^6.1.2
  qr_code_scanner: ^1.0.1
  pinput: ^5.0.1
  geolocator: ^13.0.3
  permission_handler: ^11.4.0
  advertising_id: ^2.7.1
  audioplayers: ^6.4.0
  in_app_update: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
