name: aimtech
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  provider: ^6.0.5
  qr_code_scanner: ^1.0.1
  pinput: ^5.0.1
  geolocator: ^13.0.3
  permission_handler: ^11.4.0
  advertising_id: ^2.7.1
  audioplayers: ^6.4.0
  in_app_update: ^4.2.3
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/aimtech logo.png
    - assets/sound.mp3
